# What is NumPy?

When learning NumPy we are asking questions like:

- What does this array look like right now?
- What is it's shape
- What happens if I change this operation

Jupiter notebook supports **Exploratory Workflow**

- Run code incremenetally
- See immediate feedback
- Mix explanation with code
- Experiment safely

### Importing NumPy

In [9]:
import numpy as np

## `ndarray`

EVERYTHING in NumPy revolves around this - `n-dimensional array`

In [3]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [11]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

List stores REFERENCES to objects, but ndarray store RAW numeric values

In [13]:
arr2 = np.arange(10,20,1) #generated dates - numpy prefers this over manually typed values. zeroes, ones. 3 args: first value, up until 20 (2nd arg), 3rd - how much each value increases by
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
list2 = [40,50,60]
arr3 = np.array([list1, list2])
arr3

array([[10, 20, 30],
       [40, 50, 60]])

## Shapes

In [15]:
arr3.shape

(2, 3)

# 3d example

In [19]:
arr3dim = np.array([
    [[1,2,3], [3,4,5]],
    [[5,6,7], [8,9,10]]
])

arr3dim.shape

(2, 2, 3)

# Vectorisation

In [20]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [24, 27, 30]]])

In [22]:
arr1

array([10, 20, 30])

In [23]:
list2

[40, 50, 60]

In [24]:
arr1 * np.array(list2) # elementwise - multiplying each element at the same position toger

array([ 400, 1000, 1800])

In [25]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
# arr1 and arr2 have incomptablible types.
# arr1 * arr2
# if two arrays have incompatible shapes, NumPy throws error. It wont guess what you mean
# shapes must be broadcastable or align

arr1

array([10, 20, 30])

In [35]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
nish_arr1 = np.array([
                [1,2,3],
                [4,5,6]
             ])

arr3dim_nish = np.array([10,20,30])

nish_arr1 * arr3dim_nish

array([[ 10,  40,  90],
       [ 40, 100, 180]])

## Indexing and Slicing

In [41]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [43]:
arr3[1,2]

np.int64(60)

In [44]:
arr3[1]

array([40, 50, 60])

In [46]:
arr3[:,2]

array([30, 60])

## Built in statistics

In [47]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [49]:
print(arr3.sum())

210


In [50]:
print(arr3.mean())

35.0


In [51]:
print(arr3.std())

17.07825127659933


In [52]:
print(arr3.min())

10


In [53]:
print(arr3.max())

60


# Iterations

Dont do it :)

## Saving and Loading

In [57]:
np.save("array", arr3)
np.load("array.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [60]:
np.savetxt("array",arr3)
np.loadtxt("array.txt", delimiter=",")

FileNotFoundError: array.txt not found.